export const enum PageUrl {
    ROOT = '/',
    LOGIN = '/login',
    REGISTER = '/register',
    HOME = '/home',
    NOT_FOUND = '/not-found',
    LOADING = '/loading',
    PROFILE = '/profile',
    SETTINGS = '/settings',
    ABOUT = '/about',
    CONTACT = '/contact',
    PRIVACY = '/privacy',
    TERMS = '/terms',
    HELP = '/help',
    FAQ = '/faq',
}
